# roles/ROLENAME/tasks/main.yml
---

- name: install the latest version of Monit
  yum: name=monit state=latest

- name: Configure and complete the installation process
  command: sudo {{ item }} 
  with_items:
    - firewall-cmd --add-port=2812/tcp --permanent
    - systemctl restart firewalld
    - monit

- name: copy monitrc for dashboard
  copy:
    src: monitrc
    dest: /etc/