# roles/ROLENAME/tasks/main.yml
---


	
- name: Configure monit.conf file
  copy: config file
    src: path= 
    dest: path=/etc/monit.conf
  tags: 

- name: Make id file
  file: path=/var/lib/monit/id state=touch mode=0777

- name: Make monitlog-file 
  file: path=/usr/var/log/monit.log state=touch mode=0777

- name: 
  copy:
    src: 
    dest: 
  tags: 

- unarchive: src=/home/vagrant/Yomoni.tar.gz dest=/home/vagrant copy=no

- name: Install monit
  command: sudo yum install monit

- name: Startup monit
  command: sudo service monit start

- name: Start monit with start-update
  command: sudo systemctl enable monit.service

- name: Enable Firewall for the port 2812
  command: sudo firewall-cmd --add-port=2812/tcp --permanent

- name: Restart firewall to apply changes
  command: sudo systemctl restart firewalld
  
